/**
 * @file CustomFont_Demo.ino
 * @brief Shows how to use fonts generated by the Python font converter.
 *
 * To generate a custom font:
 *   python font_converter.py --input MyFont.ttf --size 12 --output MyFont12.h
 *
 * Then include the generated header and pass it to setFont().
 */

#include <VietnameseOLED.h>
#include <drivers/SSD1306Adapter.h>
#include <fonts/Font_8x16_VN.h>

/* If you have a custom font, include it:
 * #include "MyCustomFont.h"
 */

SSD1306Adapter display(128, 64, 0x3C);
VietnameseOLED oled(display);

void setup() {
    oled.begin();
    oled.clear();

    /* Use built-in font (replace with custom font header) */
    oled.setFont(Font_8x16_VN);

    /* The API is the same regardless of which font is used */
    oled.drawUTF8(0, 0, "Phông chữ tùy chỉnh");
    oled.drawUTF8(0, 16, "Custom Font Demo");

    /* Demonstrate setScale for larger text */
    oled.setScale(2);
    oled.drawUTF8(0, 36, "Lớn");

    /* Reset scale */
    oled.setScale(1);

    oled.update();
}

void loop() {
    delay(1000);
}
